Controllers/KompaniskiSmetkiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banka.Data;
using Banka.Models;
using Banka.FilterViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Banka.Controllers
{
    public class KompaniskiSmetkiController : Controller
    {
        private readonly BankaContext _context;

        public KompaniskiSmetkiController(BankaContext context)
        {
            _context = context;
        }

        // GET: KompaniskiSmetki
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchBankarskiBroj)
        {
            IQueryable<KompaniskaSmetka> smetki = _context.KompaniskaSmetka.AsQueryable();
            

            if (!string.IsNullOrEmpty(searchBankarskiBroj))
            {
                smetki = smetki.Where(s => s.bankarskiBroj.Contains(searchBankarskiBroj));
            }

           

            smetki = smetki.Include(s => s.Firma).Include(s => s.vrabotenKoordinator).ThenInclude(s => s.vrabotenKoordinator);

            var viewmodel = new KompaniskiSmetkiFilter
            {
                KompaniskiSmetki = await smetki.ToListAsync(),
                
            };


            return View(viewmodel);
        }


        // GET: KompaniskiSmetki/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kompaniskaSmetka = await _context.KompaniskaSmetka
                .Include(k => k.vrabotenKoordinator).ThenInclude(k => k.vrabotenKoordinator)
                .Include(k => k.Firma)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kompaniskaSmetka == null)
            {
                return NotFound();
            }

            return View(kompaniskaSmetka);
        }

        // GET: KompaniskiSmetki/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["firmaId"] = new SelectList(_context.Firma, "Id", "firmName");
            return View();
        }

        // POST: KompaniskiSmetki/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,bankarskiBroj,paricnaSostojba,dataIzdavanje,tip,firmaId")] KompaniskaSmetka kompaniskaSmetka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kompaniskaSmetka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["firmaId"] = new SelectList(_context.Firma, "Id", "firmName", kompaniskaSmetka.firmaId);
            return View(kompaniskaSmetka);
        }

        // GET: KompaniskiSmetki/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kompaniskaSmetka = await _context.KompaniskaSmetka.FindAsync(id);
            if (kompaniskaSmetka == null)
            {
                return NotFound();
            }
            ViewData["firmaId"] = new SelectList(_context.Firma, "Id", "firmName", kompaniskaSmetka.firmaId);
            return View(kompaniskaSmetka);
        }

        // POST: KompaniskiSmetki/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,bankarskiBroj,paricnaSostojba,dataIzdavanje,tip,firmaId")] KompaniskaSmetka kompaniskaSmetka)
        {
            if (id != kompaniskaSmetka.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kompaniskaSmetka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KompaniskaSmetkaExists(kompaniskaSmetka.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["firmaId"] = new SelectList(_context.Firma, "Id", "firmName", kompaniskaSmetka.firmaId);
            return View(kompaniskaSmetka);
        }

        // GET: KompaniskiSmetki/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kompaniskaSmetka = await _context.KompaniskaSmetka
                .Include(k => k.vrabotenKoordinator).ThenInclude(k => k.vrabotenKoordinator)
                .Include(k => k.Firma)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kompaniskaSmetka == null)
            {
                return NotFound();
            }

            return View(kompaniskaSmetka);
        }

        // POST: KompaniskiSmetki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kompaniskaSmetka = await _context.KompaniskaSmetka.FindAsync(id);
            _context.KompaniskaSmetka.Remove(kompaniskaSmetka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KompaniskaSmetkaExists(int id)
        {
            return _context.KompaniskaSmetka.Any(e => e.Id == id);
        }
    }
}

Views/KompaniskiSmetki/Create.cshtml
@model Banka.Models.KompaniskaSmetka

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>KompaniskaSmetka</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="bankarskiBroj" class="control-label"></label>
                <input asp-for="bankarskiBroj" class="form-control" />
                <span asp-validation-for="bankarskiBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paricnaSostojba" class="control-label"></label>
                <input asp-for="paricnaSostojba" class="form-control" />
                <span asp-validation-for="paricnaSostojba" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataIzdavanje" class="control-label"></label>
                <input asp-for="dataIzdavanje" class="form-control" />
                <span asp-validation-for="dataIzdavanje" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="firmaId" class="control-label">Фирма</label>
                <select asp-for="firmaId" class="form-control" asp-items="ViewBag.firmaId">
                    <option value=" ">Select</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KompaniskiSmetki/Delete.cshtml
@model Banka.Models.KompaniskaSmetka

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KompaniskaSmetka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.bankarskiBroj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bankarskiBroj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.paricnaSostojba)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.paricnaSostojba)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dataIzdavanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dataIzdavanje)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Firma.firmName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.vrabotenKoordinator)
        </dt>
        <dd>
            @foreach (var koordinator in Model.vrabotenKoordinator)
            {
                <a asp-controller="Employees" asp-action="Details" asp-route-id="@koordinator.Id">@koordinator.vrabotenKoordinator.FullName</a><br />
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/KompaniskiSmetki/Details.cshtml
@model Banka.Models.KompaniskaSmetka

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>KompaniskaSmetka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.bankarskiBroj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bankarskiBroj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.paricnaSostojba)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.paricnaSostojba)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dataIzdavanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dataIzdavanje)
        </dd>
        
        
        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Firma.firmName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.vrabotenKoordinator)
        </dt>
        <dd>
            @foreach (var koordinator in Model.vrabotenKoordinator)
            {
                <a asp-controller="Employees" asp-action="Details" asp-route-id="@koordinator.Id">@koordinator.vrabotenKoordinator.FullName</a><br />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/KompaniskiSmetki/Edit.cshtml
@model Banka.Models.KompaniskaSmetka

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Компаниска сметка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="bankarskiBroj" class="control-label"></label>
                <input asp-for="bankarskiBroj" class="form-control" />
                <span asp-validation-for="bankarskiBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paricnaSostojba" class="control-label"></label>
                <input asp-for="paricnaSostojba" class="form-control" />
                <span asp-validation-for="paricnaSostojba" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataIzdavanje" class="control-label"></label>
                <input asp-for="dataIzdavanje" class="form-control" />
                <span asp-validation-for="dataIzdavanje" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="firmaId" class="control-label">Фирма</label>
                <select asp-for="firmaId" class="form-control" asp-items="ViewBag.firmaId"></select>
                <span asp-validation-for="firmaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KompaniskiSmetki/Index.cshtml
@model Banka.FilterViewModels.KompaniskiSmetkiFilter

@{
    ViewData["Title"] = "Index";
}

<h2>Компаниски Сметки</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="KompaniskiSmetki" asp-action="Index" method="get">
    <p>
        Банкарски број: <input type="text" asp-for="searchBankarskiBroj" />
        
        <input type="submit" value="Филтер" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KompaniskiSmetki[0].bankarskiBroj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KompaniskiSmetki[0].paricnaSostojba)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KompaniskiSmetki[0].dataIzdavanje)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.KompaniskiSmetki[0].Firma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KompaniskiSmetki[0].vrabotenKoordinator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.KompaniskiSmetki) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.bankarskiBroj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paricnaSostojba)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataIzdavanje)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Firma.firmName)
            </td>
            <td>
                @foreach(var koordinator in item.vrabotenKoordinator)
                {
                    <a asp-controller="Employees" asp-action="Details" asp-route-id="@koordinator.Id">@koordinator.vrabotenKoordinator.FullName</a><br />
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>