Controllers/FirmiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banka.Data;
using Banka.Models;
using Banka.FilterViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Banka.Controllers
{
    public class FirmiController : Controller
    {
        private readonly BankaContext _context;

        public FirmiController(BankaContext context)
        {
            _context = context;
        }

        // GET: Firmi
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchfirmName)
        {
            IQueryable<Firma> firmi = _context.Firma.AsQueryable();

            if (!string.IsNullOrEmpty(searchfirmName))
            {
                firmi = firmi.Where(f => f.firmName.Contains(searchfirmName));
            }

            firmi = firmi.Include(f => f.Sopstvenici).ThenInclude(f => f.Sopstvenik).Include(f => f.kompaniskiSmetki);

            var viewmodel = new FirmiFilter
            {
                Firmi = await firmi.ToListAsync()
            };

            return View(viewmodel);
        }

        // GET: Firmi/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma
                .Include(f => f.kompaniskiSmetki)
                .Include(f => f.Sopstvenici).ThenInclude(f => f.Sopstvenik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (firma == null)
            {
                return NotFound();
            }

            return View(firma);
        }

        // GET: Firmi/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Firmi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,firmName,dataOsnovanje,Address")] Firma firma)
        {
            if (ModelState.IsValid)
            {
                _context.Add(firma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(firma);
        }

        // GET: Firmi/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma.FindAsync(id);
            if (firma == null)
            {
                return NotFound();
            }
            return View(firma);
        }

        // POST: Firmi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,firmName,dataOsnovanje,Address")] Firma firma)
        {
            if (id != firma.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(firma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FirmaExists(firma.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(firma);
        }

        // GET: Firmi/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma
                .Include(f => f.kompaniskiSmetki)
                .Include(f => f.Sopstvenici).ThenInclude(f => f.Sopstvenik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (firma == null)
            {
                return NotFound();
            }

            return View(firma);
        }

        // POST: Firmi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var firma = await _context.Firma.FindAsync(id);
            _context.Firma.Remove(firma);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FirmaExists(int id)
        {
            return _context.Firma.Any(e => e.Id == id);
        }
    }
}

Controllers/KartickiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banka.Data;
using Banka.Models;
using Banka.FilterViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Banka.Controllers
{
    public class KartickiController : Controller
    {
        private readonly BankaContext _context;

        public KartickiController(BankaContext context)
        {
            _context = context;
        }

        // GET: Karticki
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchBrojKarticka, string searchTipKarticka)
        {
            IQueryable<Karticka> karticki = _context.Karticka.AsQueryable();
            IQueryable<string> tipKartici = _context.Karticka.OrderBy(k => k.tipNaKarticka)
                .Select(k => k.tipNaKarticka).Distinct();

            if (!string.IsNullOrEmpty(searchBrojKarticka))
            {
                karticki = karticki.Where(k => k.brojNaKarticka.Contains(searchBrojKarticka));
            }
            if(!string.IsNullOrEmpty(searchTipKarticka))
            {
                karticki = karticki.Where(k => k.tipNaKarticka == searchTipKarticka);
            }

            karticki = karticki.Include(k => k.korisnickSmetka);

            var viewmodel = new KartickiFilter
            {
                Karticki = await karticki.ToListAsync(),
                tipoviKarticki = new SelectList(await tipKartici.ToListAsync())
            };

            //var bankaContext = _context.Karticka.Include(k => k.korisnickSmetka);
            return View(viewmodel);
        }

        // GET: Karticki/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka
                .Include(k => k.korisnickSmetka)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (karticka == null)
            {
                return NotFound();
            }

            return View(karticka);
        }

        // GET: Karticki/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj");
            return View();
        }

        // POST: Karticki/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,brojNaKarticka,tipNaKarticka,paricnaSostojba,korisnickaSmetkaId")] Karticka karticka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(karticka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // GET: Karticki/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka.FindAsync(id);
            if (karticka == null)
            {
                return NotFound();
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // POST: Karticki/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,brojNaKarticka,tipNaKarticka,paricnaSostojba,korisnickaSmetkaId")] Karticka karticka)
        {
            if (id != karticka.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(karticka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KartickaExists(karticka.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // GET: Karticki/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka
                .Include(k => k.korisnickSmetka)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (karticka == null)
            {
                return NotFound();
            }

            return View(karticka);
        }

        // POST: Karticki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var karticka = await _context.Karticka.FindAsync(id);
            _context.Karticka.Remove(karticka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KartickaExists(int id)
        {
            return _context.Karticka.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banka</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Banka</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Korisnici" asp-action="Index">Корисници</a></li>
                    <li><a asp-area="" asp-controller="Firmi" asp-action="Index">Фирми</a></li>
                    <li><a asp-area="" asp-controller="Employees" asp-action="Index">Вработени</a></li>
                    <li><a asp-area="" asp-controller="KorisnickiSmetki" asp-action="Index">Кориснички Сметки</a></li>
                    <li><a asp-area="" asp-controller="KompaniskiSmetki" asp-action="Index">Компаниски Сметки</a></li>
                    <li><a asp-area="" asp-controller="Karticki" asp-action="Index">Картички</a></li>
                    <li><a asp-area="" asp-controller="FirmiSopstvenicis" asp-action="Index">Фирми со сопственици</a></li>
                    <li><a asp-area="" asp-controller="EmployeeFirms" asp-action="Index">Kоординатори</a></li>
                    <li>
                        @if(User?.Identity?.IsAuthenticated ?? false)
                        {
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Banka</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>