Controllers/KartickiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banka.Data;
using Banka.Models;
using Banka.FilterViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Banka.Controllers
{
    public class KartickiController : Controller
    {
        private readonly BankaContext _context;

        public KartickiController(BankaContext context)
        {
            _context = context;
        }

        // GET: Karticki
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchBrojKarticka, string searchTipKarticka)
        {
            IQueryable<Karticka> karticki = _context.Karticka.AsQueryable();
            IQueryable<string> tipKartici = _context.Karticka.OrderBy(k => k.tipNaKarticka)
                .Select(k => k.tipNaKarticka).Distinct();

            if (!string.IsNullOrEmpty(searchBrojKarticka))
            {
                karticki = karticki.Where(k => k.brojNaKarticka.Contains(searchBrojKarticka));
            }
            if(!string.IsNullOrEmpty(searchTipKarticka))
            {
                karticki = karticki.Where(k => k.tipNaKarticka == searchTipKarticka);
            }

            karticki = karticki.Include(k => k.korisnickSmetka);

            var viewmodel = new KartickiFilter
            {
                Karticki = await karticki.ToListAsync(),
                tipoviKarticki = new SelectList(await tipKartici.ToListAsync())
            };

            //var bankaContext = _context.Karticka.Include(k => k.korisnickSmetka);
            return View(viewmodel);
        }

        // GET: Karticki/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka
                .Include(k => k.korisnickSmetka)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (karticka == null)
            {
                return NotFound();
            }

            return View(karticka);
        }

        // GET: Karticki/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj");
            return View();
        }

        // POST: Karticki/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,brojNaKarticka,tipNaKarticka,paricnaSostojba,korisnickaSmetkaId")] Karticka karticka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(karticka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // GET: Karticki/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka.FindAsync(id);
            if (karticka == null)
            {
                return NotFound();
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // POST: Karticki/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,brojNaKarticka,tipNaKarticka,paricnaSostojba,korisnickaSmetkaId")] Karticka karticka)
        {
            if (id != karticka.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(karticka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KartickaExists(karticka.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnickaSmetkaId"] = new SelectList(_context.KorisnickaSmetka, "Id", "bankarskiBroj", karticka.korisnickaSmetkaId);
            return View(karticka);
        }

        // GET: Karticki/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var karticka = await _context.Karticka
                .Include(k => k.korisnickSmetka)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (karticka == null)
            {
                return NotFound();
            }

            return View(karticka);
        }

        // POST: Karticki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var karticka = await _context.Karticka.FindAsync(id);
            _context.Karticka.Remove(karticka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KartickaExists(int id)
        {
            return _context.Karticka.Any(e => e.Id == id);
        }
    }
}

Controllers/KorisnickiSmetkiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banka.Data;
using Banka.Models;
using Banka.FilterViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Banka.Controllers
{
    public class KorisnickiSmetkiController : Controller
    {
        private readonly BankaContext _context;

        public KorisnickiSmetkiController(BankaContext context)
        {
            _context = context;
        }

        // GET: KorisnickiSmetki
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchBankarskiBroj, string tipSmetka)
        {
            IQueryable<KorisnickaSmetka> smetki = _context.KorisnickaSmetka.AsQueryable();
            IQueryable<string> tipoviSmetki = _context.KorisnickaSmetka.OrderBy(s => s.tip)
                .Select(s => s.tip).Distinct();

            if (!string.IsNullOrEmpty(searchBankarskiBroj))
            {
                smetki = smetki.Where(s => s.bankarskiBroj.Contains(searchBankarskiBroj));
            }

            if (!string.IsNullOrEmpty(tipSmetka))
            {
                smetki = smetki.Where(s => s.tip == tipSmetka);
            }

            smetki = smetki.Include(s => s.Korisnik).Include(s => s.Karticki);

            var viewmodel = new KorisnickiSmetkiFilter
            {
                KorisnickiSmetki = await smetki.ToListAsync(),
                tipoviSmetka = new SelectList(await tipoviSmetki.ToListAsync())
            };

           
            return View(viewmodel);
        }

        // GET: KorisnickiSmetki/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnickaSmetka = await _context.KorisnickaSmetka
                .Include(k => k.Korisnik)
                .Include(k => k.Karticki)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnickaSmetka == null)
            {
                return NotFound();
            }

            return View(korisnickaSmetka);
        }

        // GET: KorisnickiSmetki/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["korisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName");
            return View();
        }

        // POST: KorisnickiSmetki/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,bankarskiBroj,paricnaSostojba,dataIzdavanje,tip,korisnikId")] KorisnickaSmetka korisnickaSmetka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(korisnickaSmetka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName", korisnickaSmetka.korisnikId);
            return View(korisnickaSmetka);
        }

        // GET: KorisnickiSmetki/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnickaSmetka = await _context.KorisnickaSmetka.FindAsync(id);
            if (korisnickaSmetka == null)
            {
                return NotFound();
            }
            ViewData["korisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName", korisnickaSmetka.korisnikId);
            return View(korisnickaSmetka);
        }

        // POST: KorisnickiSmetki/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,bankarskiBroj,paricnaSostojba,dataIzdavanje,tip,korisnikId")] KorisnickaSmetka korisnickaSmetka)
        {
            if (id != korisnickaSmetka.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(korisnickaSmetka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KorisnickaSmetkaExists(korisnickaSmetka.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName", korisnickaSmetka.korisnikId);
            return View(korisnickaSmetka);
        }

        // GET: KorisnickiSmetki/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnickaSmetka = await _context.KorisnickaSmetka
                .Include(k => k.Karticki)
                .Include(k => k.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnickaSmetka == null)
            {
                return NotFound();
            }

            return View(korisnickaSmetka);
        }

        // POST: KorisnickiSmetki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var korisnickaSmetka = await _context.KorisnickaSmetka.FindAsync(id);
            _context.KorisnickaSmetka.Remove(korisnickaSmetka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KorisnickaSmetkaExists(int id)
        {
            return _context.KorisnickaSmetka.Any(e => e.Id == id);
        }
    }
}

Views/KorisnickiSmetki/Create.cshtml
@model Banka.Models.KorisnickaSmetka

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>KorisnickaSmetka</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="bankarskiBroj" class="control-label"></label>
                <input asp-for="bankarskiBroj" class="form-control" />
                <span asp-validation-for="bankarskiBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paricnaSostojba" class="control-label"></label>
                <input asp-for="paricnaSostojba" class="form-control" />
                <span asp-validation-for="paricnaSostojba" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataIzdavanje" class="control-label"></label>
                <input asp-for="dataIzdavanje" class="form-control" />
                <span asp-validation-for="dataIzdavanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tip" class="control-label"></label>
                <input asp-for="tip" class="form-control" />
                <span asp-validation-for="tip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="korisnikId" class="control-label">Корисник</label>
                <select asp-for="korisnikId" class="form-control" asp-items="ViewBag.korisnikId">
                    <option value="">Select</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KorisnickiSmetki/Delete.cshtml
@model Banka.Models.KorisnickaSmetka

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KorisnickaSmetka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.bankarskiBroj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bankarskiBroj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.paricnaSostojba)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.paricnaSostojba)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dataIzdavanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dataIzdavanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Korisnik.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Karticki)
        </dt>
        <dd>
            @foreach(var karticka in Model.Karticki)
            {
                <a asp-controller="Karticki" asp-action="Details" asp-route-id="@karticka.Id">@karticka.brojNaKarticka</a><br />
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/KorisnickiSmetki/Details.cshtml
@model Banka.Models.KorisnickaSmetka

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>KorisnickaSmetka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.bankarskiBroj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bankarskiBroj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.paricnaSostojba)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.paricnaSostojba)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dataIzdavanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dataIzdavanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Korisnik.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Karticki)
        </dt>
        <dd>
            @foreach (var karticka in Model.Karticki)
            {
                <a asp-controller="Karticki" asp-action="Details" asp-route-id="@karticka.Id">@karticka.brojNaKarticka</a><br />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/KorisnickiSmetki/Edit.cshtml
@model Banka.Models.KorisnickaSmetka

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Корисничка сметка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="bankarskiBroj" class="control-label"></label>
                <input asp-for="bankarskiBroj" class="form-control" />
                <span asp-validation-for="bankarskiBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paricnaSostojba" class="control-label"></label>
                <input asp-for="paricnaSostojba" class="form-control" />
                <span asp-validation-for="paricnaSostojba" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataIzdavanje" class="control-label"></label>
                <input asp-for="dataIzdavanje" class="form-control" />
                <span asp-validation-for="dataIzdavanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tip" class="control-label"></label>
                <input asp-for="tip" class="form-control" />
                <span asp-validation-for="tip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="korisnikId" class="control-label">Корисник</label>
                <select asp-for="korisnikId" class="form-control" asp-items="ViewBag.korisnikId">
                    
                </select>
                <span asp-validation-for="korisnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KorisnickiSmetki/Index.cshtml
@model Banka.FilterViewModels.KorisnickiSmetkiFilter

@{
    ViewData["Title"] = "Index";
}

<h2>Кориснички сметки</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="KorisnickiSmetki" asp-action="Index" method="get">
    <p>
        Банкарски број: <input type="text" asp-for="searchBankarskiBroj"/>
        <select asp-for="tipSmetka" asp-items="Model.tipoviSmetka">
            <option value="">All</option>
        </select>
        <input type="submit" value="Филтер"/>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].bankarskiBroj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].paricnaSostojba)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].dataIzdavanje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].Korisnik)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnickiSmetki[0].Karticki)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.KorisnickiSmetki) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.bankarskiBroj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paricnaSostojba)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataIzdavanje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Korisnik.FullName)
            </td>
            <td>
                @foreach(var karticka in item.Karticki)
                {
                    <a asp-controller="Karticki" asp-action="Details" asp-route-id="@karticka.Id">@karticka.brojNaKarticka</a>
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>